### ISSUE TITLE
Create a HF Space for Simplified Launch for Testing/Demos

### ISSUE THREAD

**Issue by jessespencersmith** [vanderbilt-data-science/free-speech-app#14]
Create a notebook that simplifies the launching of the application for test/demonstration. This should have  "Open in Collab button, and should have simple instructions to allow the application to launch. We should explain that storage of logins, etc. will only persist for the duration of the run, and anything else so people are not confused when running this.

**Comment by myrandaGoesToSpace** [comment]
Decision to change to HuggingFace Space since Streamlit will not run in a notebook

**Comment by myrandaGoesToSpace** [comment]
HF Space here: https://huggingface.co/spaces/vanderbilt-dsi/free-speech-app
