### ISSUE TITLE
Create basic app interface

### ISSUE THREAD

**Issue by jessespencersmith** [vanderbilt-data-science/free-speech-app#3]

**Comment by jessespencersmith** [comment]
To support the use of a backend, use Streamlit. When coding, if you are using very recent libraries, think about Bing Chat on Edge.

**Comment by jessespencersmith** [comment]
Create a wiki with the function specifications that you are defining, look at other issues to get in the neighborhood.

**Comment by csbell-vu** [comment]
Here's a first link here: https://github.com/vanderbilt-data-science/free-speech-app/wiki/Function-Specifications

**Comment by umangchaudhry** [comment]
Closed with pull request #10
