### ISSUE TITLE
Design a backend to handle storing and retrieving  personalized information

### ISSUE THREAD

**Issue by jessespencersmith** [vanderbilt-data-science/free-speech-app#6]
Users should be able to sign in an securely store/recall the users's state principles (1 Principles Screen), the organizational principles, examples of the respondent's writing (2 Principles Screen). (See the diagram on the readme page for input widget numbers.)  

This is a design task, so the final deliverable should be a sketch of how the system would work, including handling account creation and management, interface details, storage details in a design document. From this we will prepare issues to be worked on the following sprint. If possible, please complete this by Thursday to get the issues prepared for the following sprint!

**Comment by jessespencersmith** [comment]
Create the design document as a .md file in the repository call FFS_Backend_Design.md.

**Comment by umangchaudhry** [comment]
Closed with pull request #10
